#TASK_7_ASSIGNENT_11 : PREPROCESSING OF "Data.csv"
#RANGANADH NARAYANAM
#SUBMITTED ON 04-05-2022


In [ ]:
#Data.csv

#Step 1: Importing the libraries

In [2]:
import pandas as pd
import numpy as np
import matplotlib.pyplot as plt

#Step 2: Importing dataset

In [36]:
dataset = pd.read_csv('Data.csv')
dataset.head()

Country   Age   Salary Purchased
0   France  44.0  72000.0        No
1    Spain  27.0  48000.0       Yes
2  Germany  30.0  54000.0        No
3    Spain  38.0  61000.0        No
4  Germany  40.0      NaN       Yes

In [37]:
X = dataset.iloc[:, :-1].values
y = dataset.iloc[:, :3].values

#Step 3: Handling the missing data

In [38]:
from sklearn.impute import SimpleImputer
imputer = SimpleImputer(missing_values=np.nan, strategy='mean')


In [39]:
dataset.Age.isnull().sum()

1

In [40]:
dataset.Country.isnull().sum()


0

In [41]:
dataset.Salary.isnull().sum()

1

In [54]:
from sklearn.impute import KNNImputer
imputer = KNNImputer(n_neighbors=10) 
df_data = imputer.fit_transform(dataset.iloc[:,[1,2]])

#Step 4: Encoding categorical data

In [64]:
from sklearn.preprocessing import LabelEncoder, OneHotEncoder
from sklearn.compose import ColumnTransformer
#Encode Country Column
labelencoder_X = LabelEncoder()
X[:,0] = labelencoder_X.fit_transform(X[:,0])
ct = ColumnTransformer([("Country", OneHotEncoder(), [0])], remainder = 'passthrough')
X = ct.fit_transform(X)
print(X)

[[0.0 1.0 0.0 0.0 44.0 72000.0]
 [1.0 0.0 0.0 1.0 27.0 48000.0]
 [1.0 0.0 1.0 0.0 30.0 54000.0]
 [1.0 0.0 0.0 1.0 38.0 61000.0]
 [1.0 0.0 1.0 0.0 40.0 nan]
 [0.0 1.0 0.0 0.0 35.0 58000.0]
 [1.0 0.0 0.0 1.0 nan 52000.0]
 [0.0 1.0 0.0 0.0 48.0 79000.0]
 [1.0 0.0 1.0 0.0 50.0 83000.0]
 [0.0 1.0 0.0 0.0 37.0 67000.0]]


#Step 6:Splitting the datasets into training sets and Test sets

In [65]:
from sklearn.model_selection import train_test_split 
X_train, X_test, y_train, y_test = train_test_split(X, y, test_size=0.2, random_state = 5)

#Step 7: Feature Scaling

In [ ]:
from sklearn.preprocessing import StandardScaler
scale_X = StandardScaler()
X_train = scale_X.fit_transform(X_train)
X_test = scale_X.transform(X_test)